version: "3"
services:
  fn:
    build:
      context: .
      dockerfile: Dockerfile
    image: ztj1993/fn-cli:latest
    network_mode: bridge
    environment:
      - FN_API_URL=http://172.17.0.1:8080
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/root/.fn:rw
      - ./functions:/srv:rw

  ui:
    image: fnproject/ui:latest
    network_mode: bridge
    environment:
      - FN_API_URL=http://172.17.0.1:8080
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 4000
